export const SET_RELEVANCE_DATA_REQUEST = "SET_RELEVANCE_DATA_REQUEST";
export const SET_RELEVANCE_DATA_SUCCESS = "SET_RELEVANCE_DATA_SUCCESS";
export const SET_RELEVANCE_DATA_FAILURE = "SET_RELEVANCE_DATA_FAILURE";
