export const SET_COUNTRY_DATA_REQUEST = "SET_COUNTRY_DATA_REQUEST";
export const SET_COUNTRY_DATA_SUCCESS = "SET_COUNTRY_DATA_SUCCESS";
export const SET_COUNTRY_DATA_FAILURE = "SET_COUNTRY_DATA_FAILURE";
