export const SET_INTENSITY_DATA_REQUEST = "SET_INTENSITY_DATA_REQUEST";
export const SET_INTENSITY_DATA_SUCCESS = "SET_INTENSITY_DATA_SUCCESS";
export const SET_INTENSITY_DATA_FAILURE = "SET_INTENSITY_DATA_FAILURE";
